### ISSUE TITLE
Support for x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by DariuszOstolski** [rust-lang/socket2#416] opened 2023-03-21 20:39 UTC
Hi,

It seems that since 0.5.x x86_64-unknown-linux-musl is no longer supported. Currently it doesn't compile due to  libc::DCCP_SOCKOPT_SERVICE usage which seems is not exported from muslc. I'm wondering if creating a PR to add target based on musl library would be beneficial for the community?

BR,
Dariusz

**Comment by Darksonn** [comment] 2023-03-21 20:50
This is a duplicate of #405.

**Closed** 2023-03-21 20:53 UTC
