### ISSUE TITLE
 build failed, - WebAssembly

### ISSUE THREAD

**Issue by idevorel** [rust-lang/socket2#315] opened 2022-06-19 10:20 UTC
warning: build failed, waiting for other jobs to finish...
error[E0308]: mismatched types
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/socket.rs:1776:23
     |
1776 | from!(net::TcpStream, Socket);
     |                       ^^^^^^ expected struct `Socket`, found `()`
     |
    ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

error[E0308]: mismatched types
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/socket.rs:1777:25
     |
1777 | from!(net::TcpListener, Socket);
     |                         ^^^^^^ expected struct `Socket`, found `()`
     |
    ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

error[E0308]: mismatched types
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/socket.rs:1778:23
     |
1778 | from!(net::UdpSocket, Socket);
     |                       ^^^^^^ expected struct `Socket`, found `()`
     |
    ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

error[E0308]: mismatched types
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/socket.rs:1779:15
     |
1779 | from!(Socket, net::TcpStream);
     |               ^^^^^^^^^^^^^^ expected struct `TcpStream`, found `()`
     |
    ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

error[E0308]: mismatched types
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/socket.rs:1780:15
     |
1780 | from!(Socket, net::TcpListener);
     |               ^^^^^^^^^^^^^^^^ expected struct `TcpListener`, found `()`
     |
    ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

error[E0308]: mismatched types
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/socket.rs:1781:15
     |
1781 | from!(Socket, net::UdpSocket);
     |               ^^^^^^^^^^^^^^ expected struct `UdpSocket`, found `()`
     |
    ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.4/src/lib.rs:104:16
     |
104  |             fn from(socket: $from) -> $for {
     |                ---- implicitly returns `()` as its body has no tail or `return` expression

**Comment by Thomasdezeeuw** [comment] 2022-06-19 10:41
Duplicate of https://github.com/rust-lang/socket2/issues/268.

**Closed by Thomasdezeeuw** 2022-06-19 10:41 UTC
